---
- name: Test WinRM connectivity
  hosts: windows_servers
  tasks:
    - name: Test WinRM connectivity
      win_shell: echo "WinRM is working fine"
- name: Test WinRM connectivity
  hosts: windows_servers
  win_ping:

- name: Induce an exception to see what happens
  win_ping:
    data: crash
