---
- name: Show Linux Version
  hosts: oel7
  gather_facts: yes
  gather_subset:
    - "!all"
    - "distribution"

  tasks:
    - name: Display Linux Version
      debug:
        var: ansible_distribution + " " + ansible_distribution_version
